### ISSUE TITLE
pre小技巧：强制换行与横向滚动条

### ISSUE THREAD

**Issue by chengzhx76** [chengzhx76/gist#8]
``` css
pre { 
   overflow: auto;
   overflow-y:hidden
}
```
https://blog.csdn.net/meimonkey/article/details/42268635
